name: Terraform Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    name: Terraform Plan (Dev)
    runs-on: self-hosted
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init (Dev)
        working-directory: ./Parent
        run: terraform init

      - name: Terraform Plan (Dev)
        working-directory: ./Parent
        run: terraform plan -var-file="dev.tfvars" -out=tfplan-dev

  prod:
    name: Terraform Plan+Apply (Prod)
    runs-on: self-hosted
    environment: prod   # <- yahan environment approval lagega (Settings > Environments)
    needs: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init (Prod)
        working-directory: ./Parent
        run: terraform init

      - name: Terraform Plan (Prod)
        working-directory: ./Parent
        run: terraform plan -var-file="prod.tfvars" -out=tfplan-prod

      - name: Terraform Apply (Prod)
        working-directory: ./Parent
        run: terraform apply -auto-approve tfplan-prod
