name: Terraform Deploy

on:
  push:
    branches:
      - main   # jab tum main branch me push karoge tab chalega
  workflow_dispatch: # manually bhi run kar sakte ho

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_SECRET }}
          tenant-id: ${{ secrets.AZURE_SECRET }}
          subscription-id: ${{ secrets.AZURE_SECRET }}
          client-secret: ${{ secrets.AZURE_SECRET }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

